services:
  - type: web
    name: red-product-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn red_product_backend.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.8
      - key: DATABASE_URL
        fromDatabase:
          name: red_product_db
          property: connectionString

databases:
  - name: red_product_db
    databaseName: red_product_db
    user: postgres